language: python
python:
    - "3.6"
services:
    - redis
install:
    - pip install -r requirements.txt
script:
    - cd src
    - python manage.py test
    - cd ..
    - pip install .
    - cd src
    - python manage.py migrate
    - python manage.py drc-dump
